version: '2'
services:
  mssql:
    image: microsoft/mssql-server-linux
    container_name: skwell
    ports:
      - "1433:1433"
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=P@ssw0rd
     - MSSQL_PID=Developer
    cap_add:
     - SYS_PTRACE
